fix: package.json configurations to extend correctly eslint configs
natahouse/nata-lint pull request #2
Opened 2024-03-11 19:47 UTC by Minozzzi

# [Lint] Subir pacote npm
## task: https://app.clickup.com/t/86a2e8hnf
https://www.loom.com/share/3fad84d03b3a422b99f98b22518e5399

2024-03-11 19:50 UTC, Minozzzi commented
O @TIEverton mencionou que estava com problema ao dar extend da lib, o problema era o nome do pacote e faltando a key  `main` no `package.json` conforme a documentação https://eslint.org/docs/latest/extend/shareable-configs. Corrigido o problema testei localmente com `npm link`

2024-03-11 19:50 UTC, Minozzzi commented
@RaphaelOliveiraMoura Tem contexto para avaliação do PR e deploy para o npm?

2024-03-19 21:19 UTC, andrelarocca requested changes

2024-03-19 21:19 UTC, andrelarocca commented on .npmignore
> +.gitignore
Acho que aqui tá faltando uma linha vazia ao final do arquivo!

2024-03-19 21:19 UTC, andrelarocca commented on index.js
> +module.exports = require('./react')
Aqui também faltando linha vazia!

2024-03-19 21:34 UTC, andrelarocca approved these changes

2024-03-19 21:36 UTC, merged